{% set name = "py_stringsimjoin" %}
{% set version = "0.3.5" %}
{% set sha256 = "e8b5a805c991ceb7d72ecefb3d20808dd25bdb0efac14ac415c74cad56b52ce4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # Using the GH archive as it contains the .pxd (and not the .cpp)
  # files required for Cython
  url: https://github.com/anhaidgroup/py_stringsimjoin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9a129b6ba1f5670164c13ac0bac4bab50eb0b6080080f22a225d17ff6721887e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - msinttypes  # [win and vc<14]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
  run:
    - python
    - six
    - pandas >=0.16.0
    - joblib
    - pyprind >=2.9.3
    - py_stringmatching >=0.2.1

{% set tests_to_ignore = "\"" %}
# skip test_valid_join (in 3 test files), marked @unittest.skip("Not a test")
{% set tests_to_ignore = tests_to_ignore + "not test_valid_join " %}
{% set tests_to_ignore = tests_to_ignore + "\"" %}

test:
  source_files:
    - py_stringsimjoin/tests
  imports:
    - py_stringsimjoin
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v py_stringsimjoin/tests -k {{ tests_to_ignore }}

about:
  home: https://sites.google.com/site/anhaidgroup/current-projects/magellan/py_stringsimjoin
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for string similarity joins.
  description: |
    This project seeks to build a Python software package that provides
    scalable implementation of string similarity joins over two tables,
    for commonly used similarity measures such as Jaccard, Dice, cosine,
    overlap, overlap coefficient and edit distance. 
  doc_url: https://anhaidgroup.github.io/py_stringsimjoin/
  dev_url: https://github.com/anhaidgroup/py_stringsimjoin

extra:
  recipe-maintainers:
    - pjmartinkus
