travis:
  secure:
    BINSTAR_TOKEN: ptLJ1rf70EroEKk69LZqCEkQ95EsCFX+F7vg33mPJgnhU9Lm3LN0TerElCJvsfbTg9IM4i8cesqCEQP5QowG24/nLjBExVpp1aBSilPcLZIEISbN5BnIpmU/JsezYkgCOD/3mdx/gSNtkDzmOZ7QdPNFdlkyWpliz39Aqdf5u15fhK2/grggGnM33gMm0qBRUmnwZoBJKeSh+udjim4ZPpNwAIoUcR83Yo9e5pJOcA74F3YqcBw7RgMMSbyPQPSDABn6gng743wKTQrQbVaqe/qbUl1E699CwZaW8BBjVWO89808/KvaJaCtVoHC8DnEiQUZizUq/sasj4TAdkoE4g9h9WKvrneaWCezejZprY4YJ5DM12J45p72d0RLPPoQJpdpfbl+p6LsOZXmnJnPUo6X5bjo0o99hf3MSr7HSh/9KY/n/leTVPjp5j7ME/wKhgsR4hptJp3yNLFMpJP8azG8W22NJjTJwcSUMEKjI3beI7KwJUjcT4+UlJAJSQ093xTRPGET7Ba1XEaLIH/04brPupddhKpocr/3xrMgUHRgSj5G2nRP8fIQ5RogJjHU9cCTG7p92oth9hK88mYrH3GjMgzy1D3oN78FvvbI7QoJBjZ0lQlrPeQMu3VeqEvgIOXOxQXkzSBV7pNOp1zsgsE3I2T8yRpwpBHr81TTin0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
